language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11

install:
  - wget https://raw.githubusercontent.com/eFaps/Utils/master/settings/settings.xml -O mySettings.xml
  - mvn install -s mySettings.xml -DskipTests=true -B -V

script:
  - mvn test -s mySettings.xml -B

after_success:
 - "[[ $TRAVIS_BRANCH == \"master\" || $TRAVIS_BRANCH == \"java-11\" ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests -s mySettings.xml"

